name: oracle-server-ts rpc tests
on:
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Pull latest oracle server docker image
        run: docker pull bitcoinscala/bitcoin-s-oracle-server:latest
      - name: 'Run oracle server docker image'
        run: docker run -d -p 9998:9998 bitcoinscala/bitcoin-s-oracle-server:latest
      # run typescript tests next